add cli option to (de)compress quietly
ouch-org/ouch pull request #325
Opened 2022-12-19 01:52 UTC by a-moreira

closes https://github.com/ouch-org/ouch/issues/294

2022-12-19 02:31 UTC, marcospb19 requested changes

2022-12-19 02:31 UTC, marcospb19 commented on src/opts.rs
> +    #[arg(short = 'Q', long)]
Short flag should be a lowercase 'q'.
```suggestion
    #[arg(short = 'q', long)]
```

2022-12-19 02:32 UTC, a-moreira commented on src/opts.rs
> +    #[arg(short = 'Q', long)]
you are right! :-)

2022-12-19 02:35 UTC, marcospb19 commented
quoted from https://github.com/ouch-org/ouch/issues/294#issuecomment-1356976945 
> I wasn't sure if I should send the args.quiet from the main function down the code, like it's done with the question policty and file visibility or not. Let me know what you think pls

I think it's ok to have the argument being passed like this, eventually we'll refactor if it's a problem.

I want to do some local testing here before merging, so I'll be giving another review when possible.

2022-12-24 06:13 UTC, marcospb19 approved these changes
I tested it and everything seems to be OK, just a problem with the flag not being global.

```sh
ouch --quiet compress ... # This always works
ouch compress --quiet ... # This only works with 'global = true'
ouch compress ... --quiet # This only works with 'global = true'
```

I'll fix this for --quiet and other flags too, but in another PR.

2022-12-24 06:13 UTC, merged

2022-12-24 06:14 UTC, marcospb19 commented
Thanks for the PR! :tada: :tada: :tada: